apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: shakirasadov/spring-rest-data-poc:v1.0
        ports:
        - containerPort: 80
