apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: poc
  labels:
    app: my-app
  annotations:
   prometheus.io/path: "/prometheus"
   prometheus.io/port: "8080"
   prometheus.io/scrape: "true"
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
